### ISSUE TITLE
adding .wav files?

### ISSUE THREAD

**Issue by anikalindtner** [euruband/sonic-pi-examples#2]
heya, I'm just getting through the lessons and playing around a lot with commenting stuff out / adding it bit by bit again and figured it might be nice to also be able to listen to the example I wrote. Should we also add .wav files then? Can GitHub handle .wav files anyway? I could also link to a dropbox file or sth. 

wdyt?

**Comment by pxlpnk** [comment]
`wav` files tend to become quite big and would make the repo big and hard to clone on limited bandwidth. I think putting them on soundcloud and linking them would make more sense.

**Comment by rstammer** [comment]
I'd agree to the suggestion of @pxlpnk. Adding a Soundcloud reference works fine and keeps the repo lightweight. Let's do it this way.
